// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID            pgtype.UUID
	Content       string
	ReactionCount int32
	Answered      bool
	RoomID        pgtype.UUID
}

type Room struct {
	ID    pgtype.UUID
	Theme string
}
